name: ci
on: [push]
jobs:

  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}

    strategy:
      matrix:
        include:
          - image: almalinux:latest
          - image: alpine:latest
          - image: debian:latest
          - image: fedora:latest
          - image: ubuntu:latest

    env:
      DEBIAN_FRONTEND: noninteractive
      GNULIB_REFDIR: "$HOME/.gnulib"
      GNULIB_URL: 'https://github.com/coreutils/gnulib.git'
      USER: ${{ github.repository_owner }}

    steps:
      - name: Upgrade Packages
        run: |
          . /etc/os-release
          case $ID in
              alpine) apk update && apk upgrade && apk add git tar;;
              almalinux|fedora) dnf -y upgrade && dnf -y install dnf-plugins-core git-core which;;
              debian|ubuntu) apt-get -y update && apt-get -y upgrade && apt-get -y install git;;
          esac

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Gnulib Cache Key
        run: echo "GNULIB_CACHE_KEY=`git submodule status .gnulib | sed -re 's/^.([0-9,a-f]{1,}) .*$/\1/'`" >>$GITHUB_ENV

      - name: Cache Gnulib Repository
        id: cache-gnulib
        uses: actions/cache@v3
        env:
          cache-name: cache-gnulib
        with:
          path: ${{ env.GNULIB_REFDIR }}
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.GNULIB_CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Fetch Upstream Gnulib Repository
        if: steps.cache-gnulib.outputs.cache-hit != 'true'
        run: |
          if [ -d $GNULIB_REFDIR ]; then
              cd $GNULIB_REFDIR
              git pull --ff-only
          else
              git clone $GNULIB_URL $GNULIB_REFDIR
          fi

      # bootstrap initializes submodules, so we need safe.directory
      # see: https://github.com/actions/checkout/issues/915
      - name: Bootstrap
        run: |
          git config --global --add safe.directory $(pwd)
          ./bootstrap --install-buildreqs

      - name: Configure
        run: ./configure --prefix=$RUNNER_TEMP/.local

      - name: Build
        run: make

      - name: Distribution Test
        run: make distcheck

      - name: Install
        run: make install

      - name: Configure Project Name and Version
        run: |
          echo "PROJECT_NAME=`cat .package-name`" >>$GITHUB_ENV
          echo "PROJECT_VERSION=`cat .version`" >>$GITHUB_ENV

      - name: Upload Distribution Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: distribution-artifacts
          if-no-files-found: error
          path: |
            ${{ env.PROJECT_NAME }}-${{ env.PROJECT_VERSION }}.tar.gz
            .package-name
            .version

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-test
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download Distribution Artifacts
        uses: actions/download-artifact@v3
        with:
          name: distribution-artifacts

      - name: Configure Project Name and Version
        run: |
          echo "PROJECT_NAME=`cat .package-name`" >>$GITHUB_ENV
          echo "PROJECT_VERSION=`cat .version`" >>$GITHUB_ENV

      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.PROJECT_VERSION }}
          files: ${{ env.PROJECT_NAME }}-${{ env.PROJECT_VERSION }}.tar.gz
          fail_on_unmatched_files: true
